name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: dhruvmistry200/mywebsite

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker tags
        id: tags
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "TAGS=${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:$SHORT_SHA" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image with both tags
        run: |
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$SHORT_SHA .

      - name: Test the Docker image (optional)
        run: |
          docker run -d -p 80:80 $IMAGE_NAME:latest

      - name: Push both Docker tags to GHCR
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$SHORT_SHA
