name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Build the Docker image
        run: |
          docker build -t ghcr.io/${{ github.actor }}/mywebsite:latest .

      - name: Test the Docker image
        run: |
          docker run -itd -p 80:80 ghcr.io/${{ github.actor }}/mywebsite:latest

      - name: Push the Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.actor }}/mywebsite:latest
