name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          tags: dhruvmistry200/mywebsite:latest
          push: true

      - name: Log out from Docker
        uses: docker/logout-action@v2
